/** Form checkbox értékek — egyezik a public/js/equipment-data.js EQUIPMENT_SECTIONS listáival. */
export const ALL_FORM_EQUIPMENT = [
  "4WS (összkerékkormányzás)",
  "állítható felfüggesztés",
  "állítható kormány",
  "automatikus hengerlekapcsolás",
  "centrálzár",
  "chiptuning",
  "EDC (elektronikus lengéscsillapítás vezérlés)",
  "elektromos ablak elöl",
  "elektromos ablak hátul",
  "elektromos tükör",
  "fedélzeti komputer",
  "fűthető tükör",
  "HUD / Head-Up Display",
  "kerámia féktárcsák",
  "kétoldali tolóajtó",
  "könnyűfém felni",
  "kormányváltó",
  "króm felni",
  "részecskeszűrő",
  "riasztó",
  "sebességfüggő szervokormány",
  "sperr differenciálmű",
  "sportfutómű",
  "sportülések",
  "start-stop/motormegállító rendszer",
  "szervokormány",
  "színezett üveg",
  "tolóajtó",
  "tolótető - elektromos",
  "tolótető (napfénytető)",
  "vonóhorog",
  "full extra",
  "állófűtés",
  "fűthető első ülés",
  "fűthető kormány",
  "álló helyzeti klíma",
  "bőr belső",
  "műbőr-kárpit",
  "360 fokos kamerarendszer",
  "Alcantara kárpit",
  "bőrkormány",
  "digitális műszeregység",
  "elektromos csomagtérajtó-mozgatás",
  "kulcs nélküli indítás",
  "masszírozós ülés",
  "multifunkciós kormánykerék",
  "tolatókamera",
  "tolatóradar",
  "távolsági fényszóró asszisztens",
  "függönylégzsák",
  "oldallégzsák",
  "vezetőoldali légzsák",
  "utasoldali légzsák",
  "automata fényszórókapcsolás",
  "LED fényszóró",
  "xenon fényszóró",
  "koccanásgátló",
  "sávtartó rendszer",
  "tempomat",
  "ABS (blokkolásgátló)",
  "ESP (menetstabilizátor)",
  "indításgátló (immobiliser)",
  "ISOFIX rendszer",
  "defekttűrő abroncsok",
  "GPS (navigáció)",
  "bluetooth-os kihangosító",
  "USB csatlakozó",
  "Android Auto",
  "Apple CarPlay",
  "érintőkijelző",
  "vezeték nélküli telefontöltés",
  "WiFi Hotspot",
  "defektjavító készlet",
  "otthoni hálózati töltő",
  "pótkerék",
  "tetőcsomagtartó",
  "Type2 töltőkábel",
  "garanciális",
  "azonnal elvihető",
  "első tulajdonostól",
  "garázsban tartott",
  "keveset futott",
  "nem dohányzó",
  "rendszeresen karbantartott",
  "vezetett szervizkönyv",
  "ÁFA visszaigényelhető",
  "autóbeszámítás lehetséges",
];

/** Alias → kanonikus form érték (hasznaltauto badge / leírás rövidítések). */
export const EQUIPMENT_ALIASES = [
  ["könnyűfém felni", ["alufelni", "aluminium felni", "könnyűfém", "könnyufém felni"]],
  ["bluetooth-os kihangosító", ["bluetooth", "bt"]],
  ["tempomat", ["tempomat", "sebességtartó", "acc", "adaptív tempomat"]],
  ["tolatóradar", ["parkolóradar", "parkoló asszisztens", "parkassist", "tolató radar"]],
  ["tolatókamera", ["tolatókamera", "tolató kamera", "hátsó kamera", "rear view"]],
  ["360 fokos kamerarendszer", ["360 kamera", "360 fokos", "surround view"]],
  ["bőr belső", ["bőr", "bőrkárpit", "bőrkarpit", "bőr ülés", "bőr belső"]],
  ["műbőr-kárpit", ["műbőr", "mubor"]],
  ["LED fényszóró", ["led", "ledes", "led fényszóró"]],
  ["xenon fényszóró", ["xenon", "bixenon"]],
  ["start-stop/motormegállító rendszer", ["start-stop", "start stop", "motormegállító"]],
  ["vonóhorog", ["vonóhorog", "towbar", "vonó horog"]],
  ["GPS (navigáció)", ["navigáció", "navigacio", "navigation", "gps", "navi"]],
  ["garanciális", ["garanciális", "garancia", "gyártói garancia"]],
  ["keveset futott", ["keveset futott", "alacsony futás"]],
  ["nem dohányzó", ["nem dohányzó", "nem dohanyzo", "dohányzásmentes"]],
  ["full extra", ["full extra", "fullextra", "full-extra"]],
  ["Apple CarPlay", ["carplay", "apple carplay"]],
  ["Android Auto", ["android auto"]],
  ["kulcs nélküli indítás", ["keyless", "kulcsnélküli", "kulcs nélküli"]],
  ["fűthető első ülés", ["fűthető ülés", "fűthetőülés", "üléssz fűtés", "fűtött ülés"]],
  ["fűthető kormány", ["fűthető kormány", "fűtött kormány"]],
  ["sportülések", ["sportülés", "sport ülés"]],
  ["centrálzár", ["centrálzár", "central zár", "centralzár"]],
  ["szervokormány", ["szervokormány", "servo kormány"]],
  ["elektromos ablak elöl", ["elektromos ablak", "el. ablak"]],
  ["elektromos tükör", ["elektromos tükör", "el. tükör"]],
  ["fedélzeti komputer", ["fedélzeti komputer", "onboard computer", "obc"]],
  ["riasztó", ["riasztó", "alarm"]],
  ["tolótető (napfénytető)", ["napfénytető", "napfenyteto", "tolótető"]],
  ["ABS (blokkolásgátló)", ["abs"]],
  ["ESP (menetstabilizátor)", ["esp", "asr", "menetstabilizátor"]],
  ["ISOFIX rendszer", ["isofix"]],
  ["indításgátló (immobiliser)", ["immobiliser", "indításgátló"]],
  ["sávtartó rendszer", ["sávtartó", "savtarto", "lane assist", "sávelhúzás"]],
  ["koccanásgátló", ["koccanásgátló", "front assist", "ütközés"]],
  ["USB csatlakozó", ["usb"]],
  ["érintőkijelző", ["érintőkijelző", "erintokijelzo", "touchscreen"]],
  ["vezeték nélküli telefontöltés", ["wireless charging", "wpc", "telefontöltés"]],
  ["otthoni hálózati töltő", ["wallbox", "hálózati töltő"]],
  ["Type2 töltőkábel", ["type2", "type 2 kábel"]],
  ["defekttűrő abroncsok", ["runflat", "defekttűrő"]],
  ["multifunkciós kormánykerék", ["multifunkciós kormány", "mfk"]],
  ["automata fényszórókapcsolás", ["fényszóró asszisztens", "auto light"]],
  ["távolsági fényszóró asszisztens", ["távolságifényszóró", "matrix led"]],
  ["első tulajdonostól", ["első tulaj", "1. tulajdonos"]],
  ["garázsban tartott", ["garázsban", "garazsban"]],
  ["vezetett szervizkönyv", ["szervizkönyv", "szervizkönyves"]],
  ["ÁFA visszaigényelhető", ["áfás", "afa vissza", "áfa visszaigényelhető"]],
];

export const KLIM_OPTIONS = [
  "nincs",
  "manuális klíma",
  "automata klíma",
  "digitális klíma",
  "digitális kétzónás klíma",
  "digitális többzónás klíma",
  "hőszivattyús klíma",
];
