/** Re-export — egy forrás: public/js/ingatlan-fields.js */
export {
  INGATLAN_UZLETAG,
  INGATLAN_LAKAS_TIPUS,
  INGATLAN_LAKAS_TIPUS_AIRBNB,
  INGATLAN_TIPUS_2_BY_PARENT,
  tipus2OptionsForParents,
  INGATLAN_ALLAPOT,
  INGATLAN_KORA,
  MIN_BERLETI_IDO,
  MIN_BERLETI_IDO_ROVID,
  BUTOROZOTT,
  KILATAS,
  TAJOLAS,
  FUTES,
  PARKOLAS,
  KOMFORT,
  TETOTER,
  FURDO_WC,
  EMELET,
  BELMAGASSAG,
  KOLTOZHETO,
  KOLTOZHETO_ROVID,
  IGEN_MINDEGY,
  INGATLAN_BOOL_FIELDS,
  ingatlanFormFieldCatalog,
  priceMillionOptions,
  alapteruletOptions,
  szobaszamOptions,
  arFtMinOptions,
  emeletRank,
  normalizeIngatlanUzletag,
} from "../public/js/ingatlan-fields.js";
