-- bymy — kezdeti Postgres séma (autosweb SQLite megfelelője)
-- Üres adatbázisra futtasd. Nincs adatmigráció.

CREATE EXTENSION IF NOT EXISTS citext;

-- ---------------------------------------------------------------------------
-- Hirdetések (EAV modell)
-- ---------------------------------------------------------------------------

CREATE TABLE field_defs (
  field_key TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  step INTEGER NOT NULL DEFAULT 1,
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE listings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hirdetes_cime TEXT,
  forras_url TEXT,
  hasznaltauto_hirdetes_id TEXT,
  fo_kep TEXT,
  status TEXT NOT NULL DEFAULT 'mentett',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE listing_cells (
  listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
  field_key TEXT NOT NULL,
  label TEXT NOT NULL,
  value TEXT NOT NULL,
  step INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (listing_id, field_key)
);

CREATE INDEX idx_listing_cells_listing ON listing_cells(listing_id);
CREATE INDEX idx_listings_updated ON listings(updated_at DESC);

-- ---------------------------------------------------------------------------
-- Web userek (egyelőre saját auth — később Supabase Auth lehetséges)
-- ---------------------------------------------------------------------------

CREATE TABLE web_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email CITEXT NOT NULL UNIQUE,
  password_salt TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  display_name TEXT,
  profile_json TEXT NOT NULL DEFAULT '{}',
  email_verified BOOLEAN NOT NULL DEFAULT true,
  activation_token_hash TEXT,
  activation_expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE web_sessions (
  token_hash TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES web_users(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE web_user_identities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES web_users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  provider_subject TEXT NOT NULL,
  email TEXT,
  raw_profile_json TEXT NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (provider, provider_subject)
);

CREATE INDEX idx_web_sessions_user ON web_sessions(user_id);

-- ---------------------------------------------------------------------------
-- Üzenetek / chat
-- ---------------------------------------------------------------------------

CREATE TABLE conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id TEXT NOT NULL,
  listing_title TEXT NOT NULL,
  listing_price_label TEXT NOT NULL DEFAULT '',
  listing_code TEXT NOT NULL DEFAULT '',
  listing_meta TEXT NOT NULL DEFAULT '',
  buyer_id BIGINT NOT NULL REFERENCES web_users(id) ON DELETE CASCADE,
  seller_id BIGINT NOT NULL REFERENCES web_users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  buyer_last_read_at TIMESTAMPTZ,
  seller_last_read_at TIMESTAMPTZ
);

CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  sender_id BIGINT NOT NULL REFERENCES web_users(id) ON DELETE CASCADE,
  body TEXT NOT NULL DEFAULT '',
  attachment_name TEXT,
  attachment_mime TEXT,
  attachment_path TEXT,
  attachment_size INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE message_blocks (
  blocker_id BIGINT NOT NULL REFERENCES web_users(id) ON DELETE CASCADE,
  blocked_id BIGINT NOT NULL REFERENCES web_users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (blocker_id, blocked_id)
);

CREATE TABLE device_tokens (
  user_id BIGINT NOT NULL REFERENCES web_users(id) ON DELETE CASCADE,
  token TEXT NOT NULL,
  platform TEXT NOT NULL DEFAULT 'ios',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, token)
);

CREATE TABLE push_outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES web_users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  payload_json TEXT NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_at TIMESTAMPTZ
);

CREATE INDEX idx_conversations_buyer ON conversations(buyer_id);
CREATE INDEX idx_conversations_seller ON conversations(seller_id);
CREATE INDEX idx_messages_conversation ON messages(conversation_id);
CREATE INDEX idx_push_outbox_user ON push_outbox(user_id);

-- ---------------------------------------------------------------------------
-- Partnerek / szolgáltatók
-- ---------------------------------------------------------------------------

CREATE TABLE service_categories (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE postal_codes (
  postal_code TEXT PRIMARY KEY,
  city TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lon DOUBLE PRECISION NOT NULL
);

CREATE TABLE partners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  postal_code TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lon DOUBLE PRECISION NOT NULL,
  phone TEXT NOT NULL,
  opening_hours TEXT,
  google_place_id TEXT,
  google_rating DOUBLE PRECISION,
  google_review_count INTEGER,
  is_active BOOLEAN NOT NULL DEFAULT true,
  is_paid BOOLEAN NOT NULL DEFAULT false,
  paid_until TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE partner_services (
  partner_id BIGINT NOT NULL REFERENCES partners(id) ON DELETE CASCADE,
  category_id TEXT NOT NULL REFERENCES service_categories(id),
  PRIMARY KEY (partner_id, category_id)
);

CREATE INDEX idx_partners_active_paid ON partners(is_active, is_paid);
CREATE INDEX idx_partner_services_category ON partner_services(category_id);
