-- Automatikusan generált — ne szerkeszd kézzel.
-- Futtatás: node scripts/generate-supabase-seed-sql.mjs

INSERT INTO field_defs (field_key, label, step, sort_order) VALUES
  ('uzemanyag', 'Üzemanyag', 2, 0),
  ('hirdetes_cime', 'Hirdetés címe', 1, 1),
  ('gyartasi_ev', 'Gyártási év', 1, 2),
  ('gyartasi_honap', 'Gyártási hónap', 1, 3),
  ('forgalomba_helyezes_ev', 'Első magyarországi forgalomba helyezés (év)', 1, 4),
  ('forgalomba_helyezes_honap', 'Első magyarországi forgalomba helyezés (hónap)', 1, 5),
  ('muszaki_ev', 'Műszaki vizsga érvényes (év)', 1, 6),
  ('muszaki_honap', 'Műszaki vizsga érvényes (hónap)', 1, 7),
  ('allapot', 'Állapot', 1, 8),
  ('gyartmany', 'Gyártmány', 1, 9),
  ('modell', 'Modell', 1, 10),
  ('egyeb_modell', 'Egyéb modell', 1, 11),
  ('tipus', 'Típus', 1, 12),
  ('egyeb_tipus', 'Egyéb típus', 1, 13),
  ('kivitel', 'Kivitel', 1, 14),
  ('ajtok', 'Ajtók száma', 1, 15),
  ('szemelyek', 'Szállítható szem. száma', 1, 16),
  ('okmany_jelleg', 'Okmányok jellege', 1, 17),
  ('okmany_ervenyesseg', 'Okmányok érvényessége', 1, 18),
  ('km', 'Km. óra állás', 1, 19),
  ('alvazszam', 'Alvázszám', 1, 20),
  ('rendszam', 'Rendszám', 1, 21),
  ('tulajdonosok_szama', 'Tulajdonosok száma', 1, 22),
  ('hengerurtartalom', 'Hengerűrtartalom', 2, 23),
  ('teljesitmeny_kw', 'Teljesítmény (kW)', 2, 24),
  ('teljesitmeny_le', 'Teljesítmény (LE)', 2, 25),
  ('kornyezetvedelmi', 'Környezetvédelmi oszt.', 2, 26),
  ('co2_kibocsatas', 'CO₂-kibocsátás', 2, 27),
  ('fogyasztas_varosi', 'Városi fogyasztás', 2, 28),
  ('fogyasztas_orszaguti', 'Országúti fogyasztás', 2, 29),
  ('fogyasztas_kombinalt', 'Kombinált fogyasztás', 2, 30),
  ('sebessegvalto', 'Sebességváltó', 2, 31),
  ('felezo_valto', 'Felező váltó', 2, 32),
  ('hajtas', 'Hajtás', 2, 33),
  ('henger_elrendezes', 'Henger-elrendezés', 2, 34),
  ('sajat_tomeg', 'Saját tömeg', 2, 35),
  ('ossztomeg', 'Össztömeg', 2, 36),
  ('karpit1', 'Kárpit színe (1)', 2, 37),
  ('karpit2', 'Kárpit színe (2)', 2, 38),
  ('szin', 'Szín', 2, 39),
  ('metalfeny', 'Metál', 2, 40),
  ('tetto', 'Tető', 2, 41),
  ('csomagtarto', 'Csomagtartó', 2, 42),
  ('belso_azonosito', 'Belső azonosító', 2, 43),
  ('akkumulator_kwh', 'Akkumulátor kapacitás', 2, 44),
  ('hatotav', 'Hatótáv', 2, 45),
  ('tolto_csatlakozas', 'Töltőcsatlakozó', 2, 46),
  ('nyari_gumi_szelesseg', 'Nyári gumi szélesség', 2, 47),
  ('nyari_gumi_magassag', 'Nyári gumi magasság', 2, 48),
  ('nyari_gumi_atmero', 'Nyári gumi átmérő', 2, 49),
  ('hatso_nyari_szelesseg', 'Hátsó nyári gumi szélesség', 2, 50),
  ('hatso_nyari_magassag', 'Hátsó nyári gumi magasság', 2, 51),
  ('hatso_nyari_atmero', 'Hátsó nyári gumi átmérő', 2, 52),
  ('teli_gumi_szelesseg', 'Téli gumi szélesség', 2, 53),
  ('teli_gumi_magassag', 'Téli gumi magasság', 2, 54),
  ('teli_gumi_atmero', 'Téli gumi átmérő', 2, 55),
  ('hatso_teli_szelesseg', 'Hátsó téli gumi szélesség', 2, 56),
  ('hatso_teli_magassag', 'Hátsó téli gumi magasság', 2, 57),
  ('hatso_teli_atmero', 'Hátsó téli gumi átmérő', 2, 58),
  ('klima', 'Klíma', 3, 59),
  ('nem_dohanyzo', 'Nem dohányzó', 3, 60),
  ('holgy_tulajdonos', 'Hölgy tulajdonostól', 3, 61),
  ('hitel', 'Hitel', 5, 62),
  ('kezdo_reszlet', 'Kezdőrészlet', 5, 63),
  ('havi_reszlet', 'Havi részlet', 5, 64),
  ('futamido', 'Futamidő', 5, 65),
  ('berelheto', 'Bérelhető', 5, 66),
  ('beszelt_nyelvek', 'Beszélt nyelvek', 5, 67),
  ('vetelar', 'Vételár', 5, 68),
  ('akcios_ar', 'Akciós ár', 5, 69),
  ('vetelar_eur', 'Ár (EUR)', 5, 70),
  ('forgalomba_helyezes_ar', 'Forgalomba helyezés ára', 5, 71),
  ('alkudhato', 'Alkudható', 5, 72),
  ('csere', 'Csere érdekel', 5, 73),
  ('leiras', 'Leírás', 5, 74),
  ('megye', 'Megye', 5, 75),
  ('telepules', 'Település', 5, 76),
  ('iranyitoszam', 'Irányítószám', 5, 77),
  ('megtekintesi_cim', 'Megtekintési cím', 5, 78),
  ('email_megjelenik', 'Megjelenjen az email címe', 5, 79),
  ('email', 'E-mail', 5, 80),
  ('telefon1_orszag', 'Telefon 1 országkód', 5, 81),
  ('telefon1_korzet', 'Telefon 1 körzet', 5, 82),
  ('telefon1_szam', 'Telefon 1 szám', 5, 83),
  ('telefon2_orszag', 'Telefon 2 országkód', 5, 84),
  ('telefon2_korzet', 'Telefon 2 körzet', 5, 85),
  ('telefon2_szam', 'Telefon 2 szám', 5, 86),
  ('telefon3_orszag', 'Telefon 3 országkód', 5, 87),
  ('telefon3_korzet', 'Telefon 3 körzet', 5, 88),
  ('telefon3_szam', 'Telefon 3 szám', 5, 89),
  ('video_url', 'Videó link', 5, 90),
  ('forras_url', 'Forrás URL', 5, 91),
  ('hasznaltauto_hirdetes_id', 'Hasznaltauto hirdetés azonosító', 5, 92)
ON CONFLICT (field_key) DO NOTHING;

INSERT INTO service_categories (id, label, sort_order) VALUES
  ('atiras_ugyintezes', 'Átírás ügyintézés', 1),
  ('eredetvizsga', 'Eredetvizsga', 2),
  ('muszakivizsga', 'Műszaki vizsga', 3),
  ('autoszerelo', 'Autószerelő', 4),
  ('gumiszerelo', 'Gumiszerelő', 5),
  ('lakatos', 'Lakatos', 6),
  ('klimaszerelo', 'Klímaszerelő', 7),
  ('autokozmetika', 'Autókozmetika', 8),
  ('autovillamossag', 'Autóvillamosság', 9)
ON CONFLICT (id) DO NOTHING;
