-- Bocsatech admin (level1) — elkülönítve a web_users / listings tábláktól.
-- Helyben a kód ~/.autosweb/level1.db fájlt használ.
-- Feloldás 3 hibás belépés után:
--   UPDATE level1_admins SET locked = false, failed_attempts = 0, updated_at = now()
--   WHERE username = 'a_felhasznalonev';

CREATE TABLE IF NOT EXISTS level1_admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL,
  password_salt TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  failed_attempts INTEGER NOT NULL DEFAULT 0,
  locked BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS level1_otps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  code_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_level1_otps_username ON level1_otps (username);

CREATE TABLE IF NOT EXISTS level1_sessions (
  token_hash TEXT PRIMARY KEY,
  admin_id BIGINT NOT NULL REFERENCES level1_admins(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS level1_kv (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
